name: dev-to-master-pull-request
on:
  push:
    branches:
      - dev
jobs:
  d2m:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: D2m
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: D2m
          branch: dev
          delete-branch: false
          base: master
          title: D2m
